# app/config.toml
# Configuration avancée de Chainlit

[project]
# Métadonnées de votre projet
name = "HemersonAIBuild Playground"
description = "Interface conversationnelle pour infrastructure IA souveraine"
author = "HemersonAI Team"
version = "1.0.0"

[UI]
# Configuration de l'interface utilisateur
name = "HemersonAIBuild"
description = "Votre IA Souveraine"
default_expand_messages = true
default_collapse_content = false
hide_cot = false
custom_css = "/static/custom.css"

# Personnalisation du thème
[UI.theme]
primary_color = "#667eea"
background_color = "#f8fafc"
secondary_color = "#764ba2"

[features]
# Fonctionnalités activées
upload_file = true
speech_to_text = true
text_to_speech = true
edit_message = true
unsafe_allow_html = true
latex = true

[features.audio]
# Configuration audio
enabled = true
sample_rate = 44100
chunk_duration = 1
max_duration = 300

[meta]
# Métadonnées pour le SEO
generated_by = "HemersonAI"
description = "Playground pour infrastructure IA souveraine"
image = "/static/logo.png"

[session]
# Configuration des sessions
timeout = 2700  # 45 minutes
max_size_mb = 100
persistent = false

[security]
# Configuration de sécurité
max_files = 10
max_file_size_mb = 15
allowed_origins = ["*"]
